### PR TITLE
Fix quickstart guide

### LINKED ISSUE #297: Import command creates default experiment with arbitrary artifact location `s3://fasttrackml`
When using the new `import` command, the default experiment of the output database has its artifact location set to `s3://fasttrackml/0` when it gets created, instead of what the default experiment used in the input database.

### PR DESCRIPTION
**Pull request by jgiannuzzi**
This PR updates the quickstart guide so that it can be successfully executed. Changes include:
* the default artifact root has been changed to the local filesystem instead of S3
* the installation instructions have been updated
* the instructions to run the sample have been simplified
* the `random_forest.py` example has been updated for the latest version of MLFlow
* the Poetry packages have been updated to allow the user to install everything required in one go
* the example in the README has been aligned to the one from the website
* the UI screenshot referenced in the README has been updated (the link was broken)
* the description of the project has been updated in the README
* the `import` command has now a way to specify the artifact root (fixes #297)
* the integration tests have been updated to specify the artifact root (this is needed because of #299)
* the integration tests now run in parallel 🚀

### CODE REVIEW

**Review by dave-gantenbein — DISMISSED** [review]
LGTM, I will test this all again on my mac when its merged

**Review by dave-gantenbein — APPROVED** [review]
Really this should be two PRs, but here we are, and it looks okay to me.

**Review by suprjinx — APPROVED** [review]
LGTM

**Comment by jgiannuzzi** [comment]
> Really this should be two PRs, but here we are, and it looks okay to me.

Agreed, _at least_ two 🥲

**Pull request merged**
